//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supportBotGaga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mute
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ModeratorId { get; set; }
        public string Reason { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual Moderation Moderation { get; set; }
        public virtual User User { get; set; }
    }
}
